### PR TITLE
Grid based framework

### PR DESCRIPTION
**Pull request by jubaan**
We tried to implement what we learned about bootstrap and foundation framework, we choose to make an easy to implement project without all the complexity that bootstrap or any pro framework has. Our efforts were put in making a grid system that contemplates only rows and columns.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Really fantastic work @jubaan and @ClintonEnyinna! :medal_military: 
Your project looks very clean. There is one small hiccup however, there is a small issue with the responsiveness. The aspect-ratio/initial-width for each device is a bit messy so the page starts out in a 'zoomed in' mode.

Please look into this small detail and resolve it :smile:. When this is done, please request a re-review :rocket:.

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!

### Nice job! Project looks! :+1: 
#### But there are few things that need to be corrected:

#### Responsiveness

##### Breakpoints:
First of all, the defined columns should have breakpoints (example column-large-2) . You can read about in part ["Project specific"](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59564673/)
screen

Also, This assignment consists of building a grid-based framework (similar to bootstrap) that includes some basic functionality necessary to build a website. Let`s add next properties to your project:

### Box utilities

#### Margins

*  The CSS files define separate classes for margin top, bottom, left, right, all margins and auto
*  The margins should span from `0 rem` to `1 rem`
*  The margins should have breakpoints (e.g. margin-sm-top-1)

#### Padding

*  The CSS files define separate classes for padding top, bottom, left, right, all padding and auto
*  The padding should span from `0 rem` to `1 rem`
*  The padding should have breakpoints (example padding-lg-2)

### Positioning

#### Floats

*  The CSS files define separate classes for float left, right and clearing the floats

#### Positions

*  The CSS files define separate classes to change the position property of an element to relative, absolute or fixed

### Display

#### Display properties

The CSS files define:

*  A class to set the display property of an element to flex
*  A class to set the display property to hidden
*  A class to set the display property to none
*  The none class should have breakpoints (example display-md-none)

#### Flex properties

The CSS files define:

*  Classes to set vertical alignment as top, bottom or center
*  Classes to set horizontal alignment as left, right or center

### Colors

#### Background and text

The CSS files define:

*  At least ten different classes to set the background and text colors of an element

### Text

#### Utilities

The CSS files define:

*  Classes to horizontally align text to the left, right or center
*  At least five classes to set the font size of an element
*  Three classes to set the font weight of an element (bold, normal, medium)

#### Border

*  The CSS files define separate classes for border top, bottom, left, right, all border
*  The border should span from 0 to 1rem
*  The border should have classes for making box round
*  The border should have a class defined to transform a box into a circle

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes

**Comment by jubaan** [comment]
Hi @Anna-Myzukina thanks for the great review, it is a surprise all the observations hahaha, we thought we only needed to change "one small hiccup" as @Oluwadamilareolusakin told us... We thought the complexity of the project was up to us... so we only focus on having a container with rows and columns. 

Anyways we are really thankfull for your review and have this other point of view that has raised other aspects that we can improve.

> # Really fantastic work @jubaan and @ClintonEnyinna! medal_military
> 
> Your project looks very clean. There is one small hiccup however, there is a small issue with the responsiveness. The aspect-ratio/initial-width for each device is a bit messy so the page starts out in a 'zoomed in' mode.
> 
> Please look into this small detail and resolve it smile. When this is done, please request a re-review rocket.

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Changes required!

**Comment by pelzolga123** [comment]
## Hi Team! :christmas_tree: 
### Since you haven't done required changes from previous review I will not approve this project.
### Please fix everything @Anna-Myzukina  required and submit for another review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by ClintonEnyinna** [comment]
@pelzolga123 Could you please be more specific about the changes we have to make? We've made the necessary changes Anna pointed out.

**Comment by Anna-Myzukina** [comment]
### WOW amazing job team!
#### But there are still a few things that need to be corrected:

#### Responsiveness

##### Kindly recommended to add next breakpoints:

screen

 You can read about in part ["Project specific"](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59564673/)


### Box utilities

#### Margins

*  The CSS files define separate classes for margin auto too, as I can see you added margin top, bottom, left, right, all margins.
*  Also please add properties to your margins: the margins should span from `0 rem` to `1 rem`
*  The margins should have breakpoints (e.g. margin-sm-top-1)

#### Padding

*  Kindly recommended adding padding auto.
*  The padding should span from `0 rem` to `1 rem`
*  The padding should have breakpoints (example padding-lg-2)



### Display

#### Display properties

The CSS files define:

*  The none class should have breakpoints (example display-md-none)


### Text

#### Utilities

The CSS files define:

*  Classes to horizontally align text to the left
*  Three classes to set the font weight of an element (bold, normal, medium)

#### Border

*  The border should span from 0 to 1rem
*  The border should have classes for making box round. For example as in [Bootstrap](https://getbootstrap.com/docs/4.0/utilities/borders/#border-radius)


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Nice work implementing some of the requested!
Your project still needs work on the responsiveness, please look into it. The page loads up and is zoomed in.

**Review by fatymahmed — APPROVED** [review]
## Hello @jubaan @ClintonEnyinna,
Great job on working on all requirements 👏👏
## Congratulations on completing the project.
_Go ahead and merge, don't forget to submit the project completion form._


# Status : Approved

**Comment by fatymahmed** [comment]
Hi @jubaan @ClintonEnyinna, the following changes, as mentioned by @Anna-Myzukina are optional, which means you can decide not to do them but it would be a good practice to do them ☺️.

**[OPTIONAL]**
> ### Box utilities
> #### Margins
> 
>     * The CSS files define separate classes for margin top, bottom, left, right, all margins and auto
> 
>     * The margins should span from `0 rem` to `1 rem`
> 
>     * The margins should have breakpoints (e.g. margin-sm-top-1)
> 
> 
> #### Padding
> 
>     * The CSS files define separate classes for padding top, bottom, left, right, all padding and auto
> 
>     * The padding should span from `0 rem` to `1 rem`
> 
>     * The padding should have breakpoints (example padding-lg-2)
> 
> 
> ### Positioning
> #### Floats
> 
>     * The CSS files define separate classes for float left, right and clearing the floats
> 
> 
> #### Positions
> 
>     * The CSS files define separate classes to change the position property of an element to relative, absolute or fixed
> 
> 
> ### Display
> #### Display properties
> 
> The CSS files define:
> 
>     * A class to set the display property of an element to flex
> 
>     * A class to set the display property to hidden
> 
>     * A class to set the display property to none
> 
>     * The none class should have breakpoints (example display-md-none)
> 
> 
> #### Flex properties
> 
> The CSS files define:
> 
>     * Classes to set vertical alignment as top, bottom or center
> 
>     * Classes to set horizontal alignment as left, right or center
> 
> 
> ### Colors
> #### Background and text
> 
> The CSS files define:
> 
>     * At least ten different classes to set the background and text colors of an element
> 
> 
> ### Text
> #### Utilities
> 
> The CSS files define:
> 
>     * Classes to horizontally align text to the left, right or center
> 
>     * At least five classes to set the font size of an element
> 
>     * Three classes to set the font weight of an element (bold, normal, medium)
> 
> 
> #### Border
> 
>     * The CSS files define separate classes for border top, bottom, left, right, all border
> 
>     * The border should span from 0 to 1rem
> 
>     * The border should have classes for making box round
> 
>     * The border should have a class defined to transform a box into a circle
>

**Pull request merged**
